In [3]:
import numpy as np
np.set_printoptions(linewidth=120)

I = np.array([
    [1,0],
    [0,1]
])
I4 = np.kron(I,I)

In [4]:
A = np.arange(64).reshape([4,4,4])
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [15]:
U = np.arange(16*16).reshape([16,16])

print(U)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 

In [63]:
U2 = np.arange(16*16).reshape([4,4,4,4])[:,:,0,:]
print(U2)

[[[  0   1   2   3]
  [ 16  17  18  19]
  [ 32  33  34  35]
  [ 48  49  50  51]]

 [[ 64  65  66  67]
  [ 80  81  82  83]
  [ 96  97  98  99]
  [112 113 114 115]]

 [[128 129 130 131]
  [144 145 146 147]
  [160 161 162 163]
  [176 177 178 179]]

 [[192 193 194 195]
  [208 209 210 211]
  [224 225 226 227]
  [240 241 242 243]]]


For a Unitary Matrix U = 16 x 16 matrix = |00ab> -> |i,j,k,l>

This is the element  `U.reshape([4,4,4,4])[(ij),(kl),(00),(ab)]` where the binary number $mn$ is a decimal number $0 \leq d < 4$.

In [30]:
from scipy.stats import unitary_group
from scipy.linalg import null_space

In [67]:
def U_from_A(A):
    return np.column_stack((A, null_space(A.conj().T)))


# Find northonormal vectors x that are orthogonal to all columns in A using null space of A^dag
# Append these orthonormal vectors to A as columns.
# This produces a unitary U/

In [76]:
A = unitary_group.rvs(16).reshape(4,4,4,4)[:,:,0,:]
x = U_from_A(A.reshape(16,4))
assert np.allclose(x@x.conj().T, np.eye(16))